### ISSUE TITLE
Hopefully IPv6 will be supported.

### ISSUE THREAD

**Issue by cocos56** [rejetto/hfs2#1]
IPv4 addresses are now exhausted. This have become one of the factors restricting the development of the Internet. The Chinese government and the ministry of industry and information technology are working hard on IPv6. So far, there are more than one billion IPv6 users in China. So there is an urgent need for applications that support IPv6. 

As we all know, without a global network IP address, it is difficult for others to download to the files we have shared. And in many cases, they can only access the files by connecting to the same router as us.

**Comment by cocos56** [comment]
In the IPv4 era, the addresses given to machines were private, but in the IPv6 era, they were global.

**Comment by rejetto** [comment]
hi, are you already using HFS without ipv6?
with this repo i'm currently in the process of making it work correctly as it was, as i changed the dev environment. Only then I'll be able to make improvements.
I'm not currently using ipv6 myself, and i'm not sure of what it takes to support it. I may find help from other people on github. We'll see.

**Comment by cocos56** [comment]
In the IPv4 era you can bind `0.0.0.0` represents binding all IPv4 addresses of the host, in the IPv6 era you can bind `::`  represents binding all IPv6 addresses of the host,.

**Comment by cocos56** [comment]
In China, all cell phone base stations have been retrofitted, so IPv6 is generally supported for mobile traffic. I don't know about Italy.

You can test with https://ipv6-test.com/

![image](https://user-images.githubusercontent.com/36597804/81356472-d7392f80-9103-11ea-9016-0828c432f453.png)

**Comment by cocos56** [comment]
Now I support this by running the following code on Windows :
`netsh interface portproxy add v6tov4 listenaddress=:: listenport=80 connectaddress=127.0.0.1 connectport=80`

![image](https://user-images.githubusercontent.com/36597804/81356597-21baac00-9104-11ea-9d5a-a98acbd6b911.png)

**Comment by cocos56** [comment]
You can try to access my HFS through the link below with IPv4 : 
http://sz.coco56.top:44165/
http://sz.coco56.top:39688/

**Comment by cocos56** [comment]
And try to access my HFS through the link below with IPv6 :
http://1.coco56.top/
http://5.coco56.top/

**Comment by rejetto** [comment]
I got 1Gbps home, but I also tried with my mobile connection, and for both
the test says:
IPv6 Not supported

>

**Comment by rejetto** [comment]
Still I can access your HFS on the v4 urls but not on the v6

**Comment by cocos56** [comment]
According to https://www.china-ipv6.cn/#/index 

* Italy ranks ninth in the number of IPv6 address requests worldwide. 
![3E%{5G%D UMJAXCCCOAW)$W](https://user-images.githubusercontent.com/36597804/81400339-6aec1980-915f-11ea-9fb7-30a3640b7c86.png)

* China ranks second in the number of IPv6 address requests worldwide. 
Beijing(Peking) is the capital of China, and has been completed in the development of IPv6 network on December 4, 2019. I'm from a county that has just been lifted out of poverty, and my city is not the capital also.
![X$PZAO6MRN6VP$B7ASQ(B@P](https://user-images.githubusercontent.com/36597804/81400518-e352da80-915f-11ea-87d5-2e58660035c0.png)

You can see if other network operators in your area support IPv6. Rome I feel like there's some local support. I have a feeling that some parts of Rome might support IPv6.

**Comment by cocos56** [comment]
I have an aliyun server with a golbal IPv4 address and an IPv6 private address. If you need to test IPv6, I can provide it to you.

![image](https://user-images.githubusercontent.com/36597804/81459134-e639e380-91d0-11ea-8deb-7f295481ed3c.png)

**Comment by cocos56** [comment]
You can test it with its own IPv6 address, such as `::1`, not the IPv6 addresses of other machines.

![image](https://user-images.githubusercontent.com/36597804/81459332-f8685180-91d1-11ea-9676-5642190b0aac.png)
![image](https://user-images.githubusercontent.com/36597804/81459342-0322e680-91d2-11ea-9098-9c97e3a8d495.png)

**Comment by rejetto** [comment]
> I have an aliyun server with a golbal IPv4 address and an IPv6 private address. If you need to test IPv6, I can provide it to you.

thanks for your offer!
when i'll be able to work on ipv6 we'll see how to do it.
Or other people may work on it first...

**Comment by cocos56** [comment]
Thank you, it now supports IPv6.

You can visit http://3.coco56.top/

![image](https://user-images.githubusercontent.com/36597804/82277130-b43b3500-99b9-11ea-907c-1fff93fd1cf1.png)
![image](https://user-images.githubusercontent.com/36597804/82277170-cc12b900-99b9-11ea-8109-fc6dc9d8bf36.png)

**Comment by cocos56** [comment]
But this version cannot access http://127.0.0.1/

**Comment by cocos56** [comment]
This version may only support IPv6.

**Comment by cocos56** [comment]
Can you make it support both IPv6 and IPv4 ?

**Comment by rejetto** [comment]
that was just an experiment, but the result is very interesting.
You'll probably see ipv6 + ipv4 in next beta version or in final release.

>

**Comment by rejetto** [comment]
If you have time, would you tell me which features you find that needs to be adapted for ipv6 ?
At the moment i only know of 'bans'. Thanks

**Comment by cocos56** [comment]
It applies to scenarios where resources are shared globally.

Global IPv4 addresses are now exhausted. This have become one of the factors restricting the development of the Internet.

As we all know, without a global network IP address, it is difficult for others to download to the files we have shared. And in many cases, they can only access the files by connecting to the same router as us.

In the IPv4 era, the addresses given to machines were private, but in the IPv6 era, they were global.

**Comment by rejetto** [comment]
There was a misunderstanding with my last request.
What I meant is: now that HFS will accept ipv6 requests, better than nothing but that's not enough, I will have to work on some other parts that needs to be adapted. For example, if you go to "Limits>Bans", you'll find impossible to enter ipv6 addresses, so you won't be able to use that specific feature. There may be others.
I hope it is clearer now.

**Comment by coco5666** [comment]
https://rejetto.com/wiki/index.php?title=HFS:_IP_masks

![image](https://user-images.githubusercontent.com/57277047/82434430-6ad80c00-9ac5-11ea-9089-613f8edb99fa.png)
![image](https://user-images.githubusercontent.com/57277047/82434449-70cded00-9ac5-11ea-8645-debc39292db5.png)


![image](https://user-images.githubusercontent.com/57277047/82435000-403a8300-9ac6-11ea-8204-a65f3ae89218.png)

**Comment by coco5666** [comment]
Ok, thank you. I see what you mean. I don't think there's anything special to do except Ban.

**Comment by rejetto** [comment]
> Can you make it support both IPv6 and IPv4 ?

can you tell me if this build works with both ipv6 and ipv4 ?
[hfs.zip](https://github.com/rejetto/hfs2/files/4658062/hfs.zip)

**Comment by cocos56** [comment]
> > Can you make it support both IPv6 and IPv4 ?
> 
> can you tell me if this build works with both ipv6 and ipv4 ?
> [hfs.zip](https://github.com/rejetto/hfs2/files/4658062/hfs.zip)

Only support IPv4, not support IPv6.

**Comment by rejetto** [comment]
if you tell me how to make a test myself, i will not bother you anymore
with more builds :)
maybe there's a way i can do it on my pc or in my LAN, even if the ISP is
not ready yet.
Using this last build, if i try to connect to ::1 it works, so it must not
be a good test.

>

**Comment by cocos56** [comment]
run `netstat -an`
You should get the following result :
 TCP    0.0.0.0:80             0.0.0.0:0              LISTENING
 TCP    [::]:80               [::]:0                 LISTENING

![image](https://user-images.githubusercontent.com/36597804/82642912-3db06880-9c41-11ea-9570-beacf06c517f.png)
![image](https://user-images.githubusercontent.com/36597804/82642973-57ea4680-9c41-11ea-8a86-c0feb5ea6030.png)

**Comment by rejetto** [comment]
thanks! so this should be good. Let me know
[hfs.zip](https://github.com/rejetto/hfs2/files/4667830/hfs.zip)

**Comment by cocos56** [comment]
Both Ipv4 and Ipv6 support are now fully implemented. But Ipv6 access can sometimes be slow.
![image](https://user-images.githubusercontent.com/36597804/82682644-280f6300-9c82-11ea-98a7-5aa2eff9029c.png)

**Comment by cocos56** [comment]
Maybe the performance of the machine I tested was too poor.

**Comment by rejetto** [comment]
cool! i will try to include more ipv6 support for next release.

>

**Comment by cocos56** [comment]
Ok, thank you!
