### ISSUE TITLE
Please provide header option Access-Control-Allow-Origin: *

### ISSUE THREAD

**Issue by JB-DX** [rejetto/hfs2#18]
Current browsers don't allow Cross-Origin Resource Sharing (CORS).
That's painful during development when using hfs to provide data-files.
For this hfs needs to provide the header 
  Access-Control-Allow-Origin: *

Could this be implemented, please?

Details:
https://web.dev/cross-origin-resource-sharing/
https://stackoverflow.com/questions/10636611/how-does-access-control-allow-origin-header-work

**Comment by rejetto** [comment]
Use the add header command inside the [request] event, and you should be fine

**Comment by JB-DX** [comment]
Thanks for your answer. I found menu "edit event scripts", but don't know how to do that.
Can you please advise?

**Comment by rejetto** [comment]
should be something like 
```
[request]
{.add header| Access-Control-Allow-Origin: * .}
```

for further help please refer to the documentation: menu > help, or http://rejetto.com/wiki/index.php?title=HFS:_Event_scripts

and also the forum

**Comment by JB-DX** [comment]
Thank you, 
that works now !
