### ISSUE TITLE
*.mp4 files become .bin when downloaded with some browsers

### ISSUE THREAD

**Issue by cocos56** [rejetto/hfs2#2]
`*.mp4` files become `.bin` when downloaded with some browsers.

I found a problem when I used my mobile QQ browser to download :
![image](https://user-images.githubusercontent.com/36597804/81317068-f6fa3480-90be-11ea-9ef7-533697dd4ab9.png)
![image](https://user-images.githubusercontent.com/36597804/81317267-36c11c00-90bf-11ea-86ca-d5ebdd18511e.png)

**Comment by rejetto** [comment]
this problem should be solved now
