### ISSUE TITLE
2.4 RC7 issue

### ISSUE THREAD

**Issue by ururumpo** [rejetto/hfs2#22]
i got some issue with 2.4 RC7 :

~~1. hfs can't load web page with corectly ( seems like css or template) (run with wine on raspbery pi)
but 2.3m run working well no have issue css or template.~~
2. i can't set my local ip with http://192.x.x.x in hfs application. they are always use http://localhost. seems like 192.x.x.x gone in ip address menu by default. (run with wine on raspberry pi). but if i type manual 192.x.x.x:port in web browser it's still work.
im not using external ip.

**Comment by rejetto** [comment]
i don't understand your problem number 2.
You say HFS is working on 192.* so i guess you only have problems with the URLs that are displayed.
If for some reason HFS is not showing 192.* in the "ip address" menu you can click on "custom" and enter it manually, just once.
If 192 is actually the address of your raspberry but HFS is not showing it then i guess it's a problem with Wine.

**Comment by ururumpo** [comment]
> You say HFS is working on 192.* so i guess you only have problems with the URLs that are displayed.
> If for some reason HFS is not showing 192.* in the "ip address" menu you can click on "custom" and enter it manually, just once.
> If 192 is actually the address of your raspberry but HFS is not showing it then i guess it's a problem with Wine.

thank you
