### ISSUE TITLE
How to setup browsable to users only and file downlodable to everyone?

### ISSUE THREAD

**Issue by movibeast** [rejetto/hfs2#31]
How to setup browsable to users only and file downlodable to everyone?
so if I use
domain.com/FOLDER - Only user can see who has access
domain.com/FOLDER/file.txt - can be seen and downloadable by everyone

**Comment by rejetto** [comment]
i don't think there's a direct option for that.
Anyway, if you dig a bit I know there is some way to get what you what with some small scripting.
I cannot test it myself, but I would right-click the folder I want (even root, if necessary), then "diff template", then would enter something to hack the template if you are not a user

[list panel]
{.if|%user%|{:{.section|list panel|back=1.}:}
|you shall not pass!.}

**Comment by movibeast** [comment]
worked out with this, thank you very much
