### ISSUE TITLE
how to setup domain?

### ISSUE THREAD

**Issue by movibeast** [rejetto/hfs2#32]
Hi,
I have used the custom ip option and added my domain then used cloudflare to show it but i tis not working.

do you know why?
I have used port 12400
is it related to that?

Thanks

**Comment by movibeast** [comment]
I have changed port to default but still the same

**Comment by rejetto** [comment]
"not working" is not clear enough, please elaborate

**Comment by movibeast** [comment]
https://prnt.sc/26v4j7v
I have hide the server ip with 123.123.123

![image](https://user-images.githubusercontent.com/34957562/153763135-4d14d45c-f95c-40c3-b31e-26d627fba6f7.png)


and I did setup sub-domain by adding it in "custom"

**Comment by movibeast** [comment]
http://rejetto.com/forum/index.php?topic=11504.0

**in HFS (YOU MUST BE IN EXPERT MODE):

Menu > ip adress > custom

*DON NOT INCLUDE "http://"
in the box type out the domain name...

Make sure you have proper port forwarding and a staic ip setup to the machine running hfs!**


I did this

**Comment by rejetto** [comment]
ok but this was the clear part, the unclear part was the "not working". Elaborate that please

**Comment by movibeast** [comment]
![image](https://user-images.githubusercontent.com/34957562/153765658-035b3a3c-6084-4e8f-a598-2f09ae0c2b2f.png)

this is unclear part, this is what I see on the sub-domain.

**Comment by rejetto** [comment]
sorry i don't know how cloudflare works.
HFS has almost nothing to do with the domain, it just uses it to format the links inside the window.
If you don't use it for this purpose then you don't have a reason to tell HFS your domain.
HFS works with the ip. You should probably tell cloudflare your ip.
The domain will work if the DNS service is correctly configured. In your case, with cloudflare, you may have additional configuration, but it's not in HFS.

**Comment by movibeast** [comment]
thank you very much for your time, trying to figure this out. If I could, I will write how I did so other poeple can use that.

**Comment by movibeast** [comment]
figured out, with cloudflaredns updater, I was able to solve and I had issue of port forwaring.
