### ISSUE TITLE
[Question] Indexing of VFS content ?

### ISSUE THREAD

**Issue by VegethB** [rejetto/hfs2#37]
Greetings,
At the moment I am facing a problem and I would like to understand if it is due to the possible absence of an index or cache.
I have 98gb of 23,000 files in 3250 folders, when I search, it also takes 3-5 minutes before I get results.
I think it could be due to a lack of indexes, is it possible to implement improvements from this point of view? Like some modification in the template to use.
Or is it a code-side thing of the program?
Or am I doing something wrong?

hfs2.4RC06

Specs:
DL380 G6 | x2 cpu Xeon l5630;
Windows Server 2019 x64 DC LTSC;
32GB DDR3 1033mhz;
Files on HDD sata2 active (sata3 supported);
OS un SSD "";

Screen: 
![image](https://user-images.githubusercontent.com/17975351/203140503-6f56858e-4112-4d58-a0b8-5e0143b06767.png)

Thanks in advance

**Comment by rejetto** [comment]
this is quite inherent to how hfs2 works.
i don't exclude a clever template could solve it, one that is not reloading from scratch at each change, similarly to what hfs3 does.

my suggestion is to try hfs3 at https://github.com/rejetto/hfs
I paid a lot of attention to cases with many files, and yet no indexes are involved. 
LMK

**Comment by rejetto** [comment]
your video is very interesting, i had no idea hfs3 was slower.
Would you make a test using the same vfs, that is with root in hfs2 to confirm the timing is roughly the same? don't need any video proof.
if it's confirmed I will make some testing to see how I can improve that.

**Comment by rejetto** [comment]
the time difference is frankly strange.
I suspect there may be some strange folders like "recycle bin" that hfs3 is searching too.

**Comment by rejetto** [comment]
Ok, I had some spare time and worked on the hfs3's slowness problem.
Fixed and published new version (0.26.5)

Made a final test searching a name in an archive of 32000 files, resulting in 3100 entries.
hfs 2.4rc7 took 8.6s 
hfs 3 (0.26.5) took 0.7s 🥇

deal? :D
