### ISSUE TITLE
Security concern?

### ISSUE THREAD

**Issue by nikescar1** [rejetto/hfs2#7]
Hey Rejetto,

I've been trying out HFS for the last couple days. It's been working great. Nice work!

I was curious if this [5 year old post about remote execution](https://warroom.rsmus.com/building-a-vulnerable-box-rejetto-hfs/) is still valid.

Thanks!

**Comment by rejetto** [comment]
that problem was fixed right away with the help of the person who had discovered it.
Just be sure to always use the latest version.
I advice you to use 2.4 even if it's not official yet.
