### ISSUE TITLE
Can UI be compatible with high-resolution screens?

### ISSUE THREAD

**Issue by Vixb1122** [rejetto/hfs2#8]
icon is too small on my pc (surface pro 4 with resolution 2736*1824)
![Snipaste_2020-08-28_18-25-01](https://user-images.githubusercontent.com/17810492/91551128-47dab500-e95c-11ea-8cbf-7571c43f2634.jpg)

**Comment by rejetto** [comment]
i hope someday this problem will be actually solved,
but until that day i solved myself with this simple procedure
https://www.windowscentral.com/how-improve-app-dpi-scaling-enabling-system-enhanced-feature-windows-10

**Comment by Vixb1122** [comment]
@rejetto good, that's useful.

**Comment by drapid** [comment]
One of a variants to solve the problem: https://github.com/EtheaDev/SVGIconImageList
